/*                                                                                           
*  Touch Sensing Library System Setup File                                                   
*                                                                                            
*  Auto-generated by System Setup Creator Tool                                               
*                                                                                            
*  This file contains electrode and other Touch Sensing System setup parameters              
*/                                                                                           

#ifndef __TSS_SYSTEM_SETUP_H__
#define __TSS_SYSTEM_SETUP_H__


/*********************** TSS Features Configuration **************************/

#define TSS_USE_KEYDETECTOR_VERSION            1
  
#define TSS_USE_SIMPLE_LOW_LEVEL               0

#define TSS_USE_NOISE_MODE                     0

#define TSS_USE_NOISE_SIGNAL_LOG               0

#define TSS_USE_DELTA_LOG                      1

#define TSS_USE_SIGNAL_LOG                     1

#define TSS_USE_INTEGRATION_DELTA_LOG          0

#define TSS_USE_FREEMASTER_GUI                 0

#define TSS_USE_CONTROL_PRIVATE_DATA           0

#define TSS_USE_AUTO_SENS_CALIBRATION          1

#define TSS_USE_AUTO_SENS_CALIB_INIT_DURATION  100

#define TSS_USE_AUTO_SENS_CALIB_LOW_LIMIT      0

#define TSS_USE_BASELINE_INIT_DURATION         15

#define TSS_USE_LOWPOWER_CALIBRATION           0

/* Signal Control Options */

#define TSS_USE_GPIO_STRENGTH                  0

#define TSS_USE_GPIO_SLEW_RATE                 0

#define TSS_USE_IIR_FILTER                     0

#define TSS_USE_NOISE_AMPLITUDE_FILTER         0

#define TSS_USE_SIGNAL_SHIELDING               0

#define TSS_USE_SIGNAL_DIVIDER                 0

#define TSS_USE_SIGNAL_MULTIPLIER              0

#define TSS_USE_DEFAULT_ELECTRODE_LEVEL_LOW    0

/* Function Source Definition */

#define TSS_USE_AUTOTRIGGER_SOURCE             UNUSED

#define TSS_USE_LOWPOWER_CONTROL_SOURCE        UNUSED

/* Code Size Reduction Options */ 

#define TSS_USE_DATA_CORRUPTION_CHECK          1

#define TSS_USE_TRIGGER_FUNCTION               1

#define TSS_USE_STUCK_KEY                      1

#define TSS_USE_NEGATIVE_BASELINE_DROP         1

#define TSS_USE_AUTO_HW_RECALIBRATION          1

/* Callback Definition */

#define TSS_ONFAULT_CALLBACK                   TSS_fOnFault /* Identifier of the user's OnFault callback */

#define TSS_ONINIT_CALLBACK                    TSS_fOnInit /* Identifier of the user's OnInit callback */

#define TSS_ONPROXIMITY_CALLBACK               TSS_fOnProximity /* Identifier of the user's OnProximity callback */

/* Debug Options */

#define TSS_ENABLE_DIAGNOSTIC_MESSAGES         0

/**************************** Electrode Configuration **************************/

#define TSS_N_ELECTRODES            6            /* Number of electrodes present in the system */

/* Electrode's GPIOs configuration */

#define TSS_E0_P                    A                /* Electrode port */
#define TSS_E0_B                    0                /* Electrode bit  */

#define TSS_E1_P                    A                /* Electrode port */
#define TSS_E1_B                    1                /* Electrode bit  */

/* Electrode's measurement method configuration */

#define TSS_E0_TYPE                 GPIO             /* Default GPIO Method */
#define TSS_E1_TYPE                 GPIO
#define TSS_E2_TYPE                 TSI0CH2
#define TSS_E3_TYPE                 TSI0CH1
#define TSS_E4_TYPE                 TSI0CH3
#define TSS_E5_TYPE                 TSI0CH4

/* Shield Configuration */

#define TSS_E0_SHIELD_ELECTRODE     3
#define TSS_E1_SHIELD_ELECTRODE     3
#define TSS_E2_SHIELD_ELECTRODE     3

/* Signal Normalization */

#define TSS_E0_SIGNAL_DIVIDER       2
#define TSS_E1_SIGNAL_MULTIPLIER    3

/************************** Controls Configuration ***************************/

#define TSS_N_CONTROLS              3

#define TSS_C0_TYPE                 TSS_CT_KEYPAD    /* Control type */
#define TSS_C0_ELECTRODES           {0}              /* Electrodes assigned tothe control */
#define TSS_C0_STRUCTURE            cKey0            /* Name of the C&S struct to create */
#define TSS_C0_CALLBACK             TSS1_fCallBack0  /* Identifier of the user's callback */

/* Slider Electrode Group Control */

#define TSS_C1_TYPE                 TSS_CT_SLIDER    /* Control type */
#define TSS_C1_ELECTRODES           {1,2}            /* Electrodes assigned tothe control */
#define TSS_C1_STRUCTURE            cKey1            /* Name of the C&S struct to create */
#define TSS_C1_CALLBACK             TSS1_fCallBack1  /* Identifier of the user's callback */

/* Rotary Control */

#define TSS_C2_TYPE                 TSS_CT_ROTARY    /* Control type */
#define TSS_C2_ELECTRODES           {3,4,5}              /* Electrodes assigned tothe control */
#define TSS_C2_STRUCTURE            cKey2            /* Name of the C&S struct to create */
#define TSS_C2_CALLBACK             TSS1_fCallBack2  /* Identifier of the user's callback */

/********************* Peripheral Specific Configuration *********************/

/* Timer Specific parameter */

#define TSS_HW_TIMER                FTM1             /* Defines the HW Timer */

#define TSS_SENSOR_PRESCALER        2                /* Defines the prescaler for all used Timers */
#define TSS_SENSOR_TIMEOUT          2047             /* Defines the timeout for all used Timers */
#define TSS_SENSOR_PROX_PRESCALER   1                /* Defines the prescaler for all used Timers in Proximity mode */
#define TSS_SENSOR_PROX_TIMEOUT     2047             /* Defines the timeout for all used Timers in Proximity mode */

/* TSI Specific parameters */

/* TSI Autocalibration Settings */
#define TSS_TSI_RESOLUTION               11  /* Required Bit resolution of the TSI */
#define TSS_TSI_EXTCHRG_LOW_LIMIT        1   /* Low Limit of External OSC Charge Current register value for TSI autocalibration */
#define TSS_TSI_EXTCHRG_HIGH_LIMIT       31  /* High Limit of External OSC Charge Current register value for TSI autocalibration */
#define TSS_TSI_PS_LOW_LIMIT             0   /* Low Limit of External OSC Prescaler register value for TSI autocalibration */
#define TSS_TSI_PS_HIGH_LIMIT            7   /* High Limit of External OSC Prescaler regiters value for TSI autocalibration */
/* TSI Autocalibration Settings in Proximity mode */
#define TSS_TSI_PROX_RESOLUTION          11  /* Required Bit resolution of the TSI */
#define TSS_TSI_PROX_EXTCHRG_LOW_LIMIT   1   /* Low Limit of External OSC Charge Current register value for TSI autocalibration */
#define TSS_TSI_PROX_EXTCHRG_HIGH_LIMIT  31  /* High Limit of External OSC Charge Current register value for TSI autocalibration */
#define TSS_TSI_PROX_PS_LOW_LIMIT        0   /* Low Limit of External OSC Prescaler register value for TSI autocalibration */
#define TSS_TSI_PROX_PS_HIGH_LIMIT       7   /* High Limit of External OSC Prescaler regiters value for TSI autocalibration */
/* Active Mode Clock Settings */
#define TSS_TSI_AMCLKS              0   /* Set Input Active Mode Clock Source ( 0 = BUSclk, 1 = MCGIRCLK, 2 = OSCERCLK, 3 - NA ) */
#define TSS_TSI_AMPSC               0   /* Set Input Active Mode Clock Prescaler ( 0 = divide 1, 7 = divide 128 ) */
#define TSS_TSI_AMCLKDIV            1   /* Set Input Active Mode Clock Divider ( 0 = divide 1, 1 = divide 2048 ) */
#define TSS_TSI_SMOD                216 /* Set Scan Modulo ( 0 - 255 ) */  
/* Low Power TSI definition */
#define TSS_TSI_LPCLKS              0  /* Set Low Power Mode Clock Source ( 0 = LPOCLK, 1 = VLPOSCCLK ) */
#define TSS_TSI_LPSCNITV            8  /* Set Low Power Mode Scan Interval ( 0 = 1ms, 15 = 500ms ) */  

#endif /*__TSS_SYSTEM_SETUP_H__*/
